### ISSUE TITLE
Can't open some file

### ISSUE THREAD

**Issue by HaojunSang** [OpenSiPM/sipm-bias-control#5]
I can't open some files of this project even use the newest KiCad (Ver5.1.9),so I need to know how to open this project correctly.
![image](https://user-images.githubusercontent.com/88612928/128626898-5068f322-f6ae-4ba1-9a37-57f6fc57d94d.png)

**Comment by mgiacomelli** [comment]
We are using the KiCAD development (5.99) branch.  5.1 is the stable branch and doesn't support projects made with the newer branch.
